language: node_js
node_js:
- "6"
- "node"
services:
- docker
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
  # Updating NPM to relevant version >= 3 on Node.JS LTS
- npm i -g npm@^3
script:
- npm run lint
- npm run test
- npm run build:docker
sudo: required
addons:
  apt:
    packages:
    - sshpass
after_success:
- mv dist $TRAVIS_BRANCH
- tar -czf build.tgz $TRAVIS_BRANCH
- export SSHPASS=$DEPLOY_PASS
- sshpass -e scp -o stricthostkeychecking=no build.tgz $DEPLOY_USER@$DEPLOY_HOST:./
- sshpass -e ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST ./deploy-build.sh
